---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bengkel1/subdomains/dompet.wan.bengkelhp.com
    - /bin/cp -R public/* $DEPLOYPATH/
    - /bin/cp -R app $DEPLOYPATH/
    - /bin/cp -R bootstrap $DEPLOYPATH/
    - /bin/cp -R config $DEPLOYPATH/
    - /bin/cp -R database $DEPLOYPATH/
    - /bin/cp -R resources $DEPLOYPATH/
    - /bin/cp -R routes $DEPLOYPATH/
    - /bin/cp -R storage $DEPLOYPATH/
    - /bin/cp composer.json $DEPLOYPATH/
    - /bin/cp composer.lock $DEPLOYPATH/
    - /bin/cp artisan $DEPLOYPATH/
    - /bin/cp .env.example $DEPLOYPATH/.env