stages:
  - test

test:
  stage: test
  image: php:8.2-cli
  script:
    - echo "Basic validation passed"
    - php --version
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"